# Project information
site_name: '盈烁SDK-PHP使用手册'
site_description: 'PHP版本帮助手册'
site_author: 'Jerry.K'

pages:
    - 使用帮助: index.md
    - 配置读取命令: config.md

# Configuration
theme:
  name: 'material'
  

